print("                                 00000000000000000000000000        ")
print("                               000                        000        ")
print("                             000                            000 ")
print("                           000                                000  ")
print("                         000                                    000   ")
print("                        000                                       000   ")
print("                       000                                          000   ")
print("                     000                                             000   ")
print("                    000                                                000   ")
print("                   000                                                   000   ")
print("                 000                                                      000   ")
print("              000                                                          000   ")
print("             000                                                             000   ")
print("           000                                                                  000   ")
print("         000                                                                      000   ")
print("        000                                                                         000   ")
print("      000                                                                             000   ")
print("     000                                                                                000   ")
print("    000                                                                                 000   ")
print("   000                                                                                    000   ")
print("   000                                                                                      000   ")
print("  000                                                                                        000   ")
print("  000                           I dont think this counts as                                    000   ")
print("  000                                Changing the world                                          000   ")
print("  000                     (I only know how to do print statements)                              000   ")
print("  000                                                                                          000   ")
print("   000                                                                                        000   ")
print("   000                                                                                       000   ")
print("    000                                                                                   000   ")
print("     000                                                                                000   ")
print("      000                                                                             000   ")
print("        000                                                                          000   ")
print("          000                                                                      000   ")
print("             000                                                                 000   ")
print("               000                                                             000   ")
print("                  000                                                        000   ")
print("                    000                                                    000   ")
print("                      000                                                000   ")
print("                        000                                           000   ")
print("                           000                                       000   ")
print("                             000                                   000   ")
print("                               000                              000   ")
print("                                  000                         000   ")
print("                                     000                    000   ")
print("                                        000000000000000000000   ")
